apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml

namespace: default

commonLabels:
  app.kubernetes.io/managed-by: flux

generatorOptions:
  disableNameSuffixHash: true
